nextflow-io/nf-schema

CHANGELOG.md
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/ExistsEvaluator.groovy
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/FormatDirectoryPathEvaluator.groovy
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/FormatFilePathEvaluator.groovy
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/FormatFilePathPatternEvaluator.groovy
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/FormatPathEvaluator.groovy
plugins/nf-schema/src/test/nextflow/validation/ValidateParametersTest.groovy

Similar to AWS, Azure and GCP do not handle empty files and directories very well (because they aren't real!). This PR ignores them in the same manner as AWS S3 blob storage.
Should fix #16

Do not validate Azure or GCP storage paths

---

docs/samplesheets/samplesheetToList.md
mkdocs.yml

Docs: Fix edit link

---

.gitignore
docs/samplesheets/samplesheetToList.md

Follow on from https://github.com/nextflow-io/nf-schema/pull/33

Sample sheet channel factory docs tweaks

---

CHANGELOG.md
plugins/nf-schema/build.gradle
plugins/nf-schema/src/resources/META-INF/MANIFEST.MF

Fix org.json vulnerability

---

CHANGELOG.md
docs/migration_guide.md
docs/nextflow_schema/create_schema.md
docs/nextflow_schema/nextflow_schema_specification.md
examples/paramsHelp/pipeline/nextflow_schema.json
examples/paramsSummaryLog/pipeline/nextflow_schema.json
examples/paramsSummaryMap/pipeline/nextflow_schema.json
examples/validateParameters/pipeline/nextflow_schema.json
examples/validationFailUnrecognisedParams/pipeline/nextflow_schema.json
examples/validationWarnUnrecognisedParams/pipeline/nextflow_schema.json
parameters_meta_schema.json
plugins/nf-schema/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-schema/src/resources/META-INF/MANIFEST.MF
plugins/nf-schema/src/testResources/nextflow_schema.json
plugins/nf-schema/src/testResources/nextflow_schema_draft7.json
plugins/nf-schema/src/testResources/nextflow_schema_file_path_pattern.json
plugins/nf-schema/src/testResources/nextflow_schema_required_numerics.json
plugins/nf-schema/src/testResources/nextflow_schema_with_deeply_nested_samplesheet.json
plugins/nf-schema/src/testResources/nextflow_schema_with_exists_false.json
plugins/nf-schema/src/testResources/nextflow_schema_with_samplesheet.json
plugins/nf-schema/src/testResources/nextflow_schema_with_samplesheet_converter.json
plugins/nf-schema/src/testResources/nextflow_schema_with_samplesheet_no_header.json
plugins/nf-schema/src/testResources/nextflow_schema_with_samplesheet_no_meta.json
plugins/nf-schema/src/testResources/nextflow_schema_with_samplesheet_uniqueEntries.json

Definitions in JSON schema draft 2020-12 should be `$defs` instead of `defs` (if we want to follow the guidelines set up by JSON schema). This PR fixes that while keeping backwards compatibility for `defs`
https://json-schema.org/understanding-json-schema/structuring#defs

support $defs

---

CHANGELOG.md
docs/configuration/configuration.md
plugins/nf-schema/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-schema/src/main/nextflow/validation/Utils.groovy
plugins/nf-schema/src/main/nextflow/validation/config/HelpConfig.groovy
plugins/nf-schema/src/main/nextflow/validation/config/SummaryConfig.groovy
plugins/nf-schema/src/main/nextflow/validation/config/ValidationConfig.groovy
plugins/nf-schema/src/test/nextflow/validation/ParamsSummaryLogTest.groovy

This PR adds two new features:
1. A way to add some text before and after the output of the `paramsSummaryLog()` function. (`validation.summary.beforeText` and `validation.summary.afterText` configuration options)
2. Automatic color filters for all `beforeText`, `afterText` and `command` configuration options
Fixes #43

`beforeText` and `afterText` for summary logs + color filter

---

CHANGELOG.md
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/UniqueEntriesEvaluator.groovy

The UniqueEntriesEvaluator does not seem to correctly detect non-unique combinations, at least in my testing. This fix ensures that the combination of values for the given keys is unique across all objects in the array.

Fix the uniqueEntries filtering

---

CHANGELOG.md
docs/configuration/configuration.md
docs/parameters/validation.md
plugins/nf-schema/src/main/nextflow/validation/config/ValidationConfig.groovy
plugins/nf-schema/src/test/nextflow/validation/ValidateParametersTest.groovy

Users may run into issues when using both `nf-schema` and `nf-test`: specifically, if `validation.failUnrecognisedParams = true`, the output directory produced by `nf-test` is an unrecognized parameter unless explicitly ignored.
This PR adds `nf_test_output` (default output directory produced by `nf-test`) as an ignored parameter for `nf-schema`. This PR adds a test and updates docs and the CHANGELOG.md.

feat: add nf_test_output to ignoreParams

---

CHANGELOG.md
plugins/nf-schema/src/main/nextflow/validation/SamplesheetConverter.groovy
plugins/nf-schema/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-schema/src/test/nextflow/validation/SamplesheetConverterTest.groovy

Fix using `samplesheetToList` multiple times in channel operators

---

CHANGELOG.md
docs/configuration/configuration.md
plugins/nf-schema/src/main/nextflow/validation/SamplesheetConverter.groovy
plugins/nf-schema/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-schema/src/main/nextflow/validation/config/SummaryConfig.groovy
plugins/nf-schema/src/main/nextflow/validation/config/ValidationConfig.groovy
plugins/nf-schema/src/test/nextflow/validation/ParamsSummaryLogTest.groovy
plugins/nf-schema/src/test/nextflow/validation/SamplesheetConverterTest.groovy

Adds two new configuration options:
1. `validation.failUnrecognisedHeaders` which will fail when unrecognised headers have been detected in the samplesheet instead of emitting a warning
2. `validation.summary.hideParams` which takes a list of parameters to exclude from the summary created by the plugin

Add extra config options

---

plugins/nf-schema/src/main/nextflow/validation/JsonSchemaValidator.groovy
plugins/nf-schema/src/main/nextflow/validation/SamplesheetConverter.groovy
plugins/nf-schema/src/main/nextflow/validation/SchemaValidator.groovy

Remove static from all places where it's actually causing problems. This should fix a lot of race conditions introduced when running the functions in channel operators

Fix race conditions

---

CHANGELOG.md
plugins/nf-schema/build.gradle
plugins/nf-schema/src/test/nextflow/validation/ValidateParametersTest.groovy
plugins/nf-schema/src/testResources/nextflow_schema.json

add missing depedency for email format support

---

CHANGELOG.md
README.md
docs/configuration/configuration.md
docs/nextflow_schema/nextflow_schema_specification.md
plugins/nf-schema/build.gradle
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/FormatDirectoryPathEvaluator.groovy
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/FormatFilePathEvaluator.groovy
plugins/nf-schema/src/main/nextflow/validation/CustomEvaluators/FormatPathEvaluator.groovy
plugins/nf-schema/src/main/nextflow/validation/JsonSchemaValidator.groovy
plugins/nf-schema/src/main/nextflow/validation/SamplesheetConverter.groovy
plugins/nf-schema/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-schema/src/main/nextflow/validation/config/SummaryConfig.groovy
plugins/nf-schema/src/main/nextflow/validation/config/ValidationConfig.groovy
plugins/nf-schema/src/resources/META-INF/MANIFEST.MF
plugins/nf-schema/src/test/nextflow/validation/ParamsSummaryLogTest.groovy
plugins/nf-schema/src/test/nextflow/validation/SamplesheetConverterTest.groovy
plugins/nf-schema/src/test/nextflow/validation/ValidateParametersTest.groovy
plugins/nf-schema/src/testResources/nextflow_schema.json

All changes in this PR have been approved before in other PRs :)

Release 2.2.0

---

plugins/nf-schema/src/main/nextflow/validation/ValidationExtension.groovy
plugins/nf-schema/src/main/nextflow/validation/ValidationObserver.groovy
plugins/nf-schema/src/main/nextflow/validation/ValidationObserverFactory.groovy
plugins/nf-schema/src/resources/META-INF/extensions.idx

Moves the help message code from the extension point to an observer. This will fix the occassion when a user only wants to use the help message without using any functions of the plugin. 
Previously the help message would only be created once a function was imported.
This PR also updates some class names to have them make more sense.

Move the help message code to an observer

---

CHANGELOG.md
plugins/nf-schema/src/main/nextflow/validation/samplesheet/SamplesheetConverter.groovy
plugins/nf-schema/src/main/nextflow/validation/utils/Common.groovy
plugins/nf-schema/src/test/nextflow/validation/SamplesheetConverterTest.groovy
plugins/nf-schema/src/testResources/samplesheet_schema_deeply_nested_anyof.json

This PR fixes some issues encountered in the validation of nested files

Fix samplesheet nesting issues

---

mkdocs.yml

- Homepage outside of a group, to help mobile nav
- Moved background + migration into renamed 'introduction' section
This should fix #102 as the homepage no longer opens inside a nested nav group on mobile:
https://github.com/user-attachments/assets/05e5af87-e584-43dc-80da-51514c41ec74

Navbar: Reorganise

---

CHANGELOG.md
plugins/nf-schema/src/main/nextflow/validation/parameters/ParameterValidator.groovy
plugins/nf-schema/src/main/nextflow/validation/samplesheet/SamplesheetConverter.groovy
plugins/nf-schema/src/main/nextflow/validation/utils/Common.groovy
plugins/nf-schema/src/main/nextflow/validation/validators/JsonSchemaValidator.groovy
plugins/nf-schema/src/main/nextflow/validation/validators/evaluators/SchemaEvaluator.groovy
plugins/nf-schema/src/test/nextflow/validation/HelpMessageCreatorTest.groovy
plugins/nf-schema/src/test/nextflow/validation/ValidateParametersTest.groovy
plugins/nf-schema/src/testResources/nextflow_schema.json

`patternProperties` were already supported by the plugin but previously due to the way we detected expected vs supplied params we did not correctly detect `patternProperties` supplied and this would cause a warning about invalid parameters (which could be an error if `failUnrecognised` was enabled).
This PR switches to using the annotations of the jsonschema validation result to look at which values actually got evaluated (and thus recognised). 
Due to needing the validation result object I did this in the `validateObject` method of our json schema validator class and just return an extra list value. This is simply ignored by samplesheet validation which does not account for this. Similarly it is not used if we validate a schema within a schema, but unrecognised parameter warning were …

Allow `patternProperties` to with parameter validation

---

CHANGELOG.md
docs/configuration/configuration.md
plugins/nf-schema/src/main/nextflow/validation/config/ValidationConfig.groovy
plugins/nf-schema/src/main/nextflow/validation/validators/JsonSchemaValidator.groovy
plugins/nf-schema/src/test/nextflow/validation/ValidateParametersTest.groovy

Fixes #80 
This PR adds the `validation.maxValueLength` option that takes an integer (bigger than or equal to 0) as input and uses this to limit the amount of characters that a value can be in error messages.
Example:
with `validation.maxValueLength = 20`
```
* --test (abcdefghij...qrstuvwxyz): Value is [string] but should be [integer]
```
Where the original value is 26 characters long (`abcdefghijklmnopqrstuvwxyz`)
The default of this option is `150` which should prevent the loss of most data, but I'm of course open to discuss lowering or raising this default

Add a config option to limit the max amount of characters for a value shown in error messages

---

CHANGELOG.md
docs/validate/validate.md
mkdocs.yml
plugins/nf-schema/src/main/nextflow/validation/ValidationExtension.groovy
plugins/nf-schema/src/main/nextflow/validation/validators/JsonSchemaValidator.groovy
plugins/nf-schema/src/test/nextflow/validation/ValidateTest.groovy
plugins/nf-schema/src/testResources/boolean_schema.json
plugins/nf-schema/src/testResources/integer_schema.json
plugins/nf-schema/src/testResources/string_schema.json

This PR adds a new function that can be used to validate common data structures (like maps, lists, strings...) against a JSON schema

Add a `validate` function

---

.github/workflows/build.yml
gradle/wrapper/gradle-wrapper.properties

This PR bumps the used gradle version to 8.13 to allow compiling in Java v21+

Fix compile issues in java 21+

---

CHANGELOG.md
README.md
build.gradle
src/main/groovy/nextflow/validation/config/HelpConfig.groovy
src/main/groovy/nextflow/validation/config/SummaryConfig.groovy
src/main/groovy/nextflow/validation/config/ValidationConfig.groovy
src/test/groovy/nextflow/validation/ConfigTest.groovy

This PR fixes an issue in `2.4.0` that would not correctly recognize `GString`s as valid inputs for the `String` config options.

fix config validation for GString values

---

CHANGELOG.md
build.gradle
src/main/groovy/nextflow/validation/parameters/ParameterValidator.groovy
src/test/groovy/nextflow/validation/ValidateParametersTest.groovy

This PR fixes a bug where unrecognized nested parameters weren't correctly ignored.
Example:
config:
```groovy
validation.defaultIgnoreParams = [ "genomes" ]
```
This would not correctly catch all parameters inside of the `genomes` map and would show a very big warning at the start of the pipeline run

Correctly ignore nested params

---

CHANGELOG.md
src/main/groovy/nextflow/validation/validators/JsonSchemaValidator.groovy

Fixes #144 
This PR prevents detection of unevaluated parameters on validation failure. The `.getAnnotation()` method returns an empty list on failure, causing all parameters to be considered invalid instead of only the unrecognised ones.
@awgymer could you take a look at this since this touches code your wrote?

Prevent invalid parameters to be printed out on validation failure

---

CHANGELOG.md
src/main/groovy/nextflow/validation/samplesheet/SamplesheetConverter.groovy
src/main/groovy/nextflow/validation/utils/Common.groovy
src/test/groovy/nextflow/validation/SamplesheetConverterTest.groovy
src/testResources/samplesheet_defaults.yaml
src/testResources/schema_input_defaults.json

Fixes #163 
This PR adds a new method `hasDeepKey` which checks if a certain key is set before fetching the value with `findDeep`. This will prevent us doing checks on the default value in this case and replace it with an exist check for the `default` key

Fix default value `null` not being set correctly

---

CHANGELOG.md
src/main/groovy/nextflow/validation/ValidationExtension.groovy
src/main/groovy/nextflow/validation/parameters/ParameterValidator.groovy
src/main/groovy/nextflow/validation/samplesheet/SamplesheetConverter.groovy
src/main/groovy/nextflow/validation/validators/JsonSchemaValidator.groovy
src/main/groovy/nextflow/validation/validators/ValidationResult.groovy
src/main/groovy/nextflow/validation/validators/ValidatonResult.groovy
src/main/groovy/nextflow/validation/validators/evaluators/SchemaEvaluator.groovy

This PR introduces a new class: `ValidationResult`. This is a wrapper around the underlying `jsonschema` validation result class and makes error handling and parsing of the result object cleaner and easier to extend in future. 
It will allow us to add functionality for e.g. parsing the annotation tree to locate all file-path type keys. 
All tests should be passing unaffected. 
This also simplifies the entry point for `Validator.validate` to a single method which takes any `Object`.

Refactor validation result handling
